export const SET_CURRENT_PAGE_NEWS = 'SET_CURRENT_PAGE_NEWS';
export const SET_CURRENT_PAGE_PODCAST = 'SET_CURRENT_PAGE_PODCAST';
export const SET_CURRENT_CATEGORY_PODCAST = 'SET_CURRENT_CATEGORY_PODCAST';
export const SET_CURRENT_CATEGORY_SIZE = 'SET_CURRENT_CATEGORY_SIZE';
export const SET_SHOW_POPUP = 'SET_SHOW_POPUP';